import { describe, expect, it, vi } from "vitest";

import {
  buildInitialFriendLinkComment,
  mergeFriendLinkIntoYaml,
  parseFriendLinkIssueBody,
  shouldReviewIssue,
  verifyReciprocalLink,
  WOODFISH_FRIEND_LINK,
} from "../src/friend-link-bot.js";

describe("friend link bot", () => {
  it("parses friend link issue bodies generated by the blog form", () => {
    const parsed = parseFriendLinkIssueBody([
      "## Friend Link Application",
      "",
      "- Site Name: 灵的梦境",
      "- Site URL: https://lemonadorable.github.io/",
      "- Friend Page URL: https://lemonadorable.github.io/links/",
      "- Avatar URL: https://lemonadorable.github.io/favicon/favicon.gif",
      "- Short Description: 愿美梦成真",
      "- Your Name / Contact: lemon",
    ].join("\n"));

    expect(parsed).toEqual({
      siteName: "灵的梦境",
      siteUrl: "https://lemonadorable.github.io/",
      friendPageUrl: "https://lemonadorable.github.io/links/",
      avatarUrl: "https://lemonadorable.github.io/favicon/favicon.gif",
      description: "愿美梦成真",
      contact: "lemon",
    });
  });

  it("rejects issue bodies without an explicit friend page URL", () => {
    const parsed = parseFriendLinkIssueBody([
      "## Friend Link Application",
      "",
      "- Site Name: Lazy Blog",
      "- Site URL: https://lazy.example/",
      "- Avatar URL: https://lazy.example/avatar.png",
      "- Short Description: client rendered links",
      "- Your Name / Contact: lazy",
    ].join("\n"));

    expect(parsed).toBeNull();
  });

  it("builds the one-hour reciprocal-link reminder comment", () => {
    const comment = buildInitialFriendLinkComment(WOODFISH_FRIEND_LINK);

    expect(comment).toContain("1 小时后");
    expect(comment).toContain("名字：woodfish");
    expect(comment).toContain("描述：我喜欢你");
    expect(comment).toContain(`头像：${WOODFISH_FRIEND_LINK.avatar}`);
    expect(comment).toContain("友链页链接");
  });

  it("waits at least one hour from issue creation before review", () => {
    const createdAt = "2026-06-07T08:00:00.000Z";

    expect(shouldReviewIssue(createdAt, new Date("2026-06-07T08:59:59.000Z"))).toBe(false);
    expect(shouldReviewIssue(createdAt, new Date("2026-06-07T09:00:00.000Z"))).toBe(true);
  });

  it("checks only the explicit friend page URL for reciprocal links", async () => {
    const fetchText = vi.fn(async (url: string) => {
      if (url === "https://example.com/links") {
        return [
          '<a href="/nested-friends">友情链接</a>',
          `<a href="${WOODFISH_FRIEND_LINK.link}">woodfish</a>`,
        ].join("\n");
      }
      return "";
    });

    const result = await verifyReciprocalLink(
      "https://example.com/links",
      WOODFISH_FRIEND_LINK,
      { fetchText },
    );

    expect(result.found).toBe(true);
    expect(result.matchedUrl).toBe("https://example.com/links");
    expect(fetchText).toHaveBeenCalledWith("https://example.com/links");
    expect(fetchText).toHaveBeenCalledTimes(1);
  });

  it("does not follow nested friend-page candidates from the explicit friend page", async () => {
    const fetchText = vi.fn(async (url: string) => {
      if (url === "https://example.com/links") {
        return '<a href="/nested-friends">友情链接</a>';
      }
      if (url === "https://example.com/nested-friends") {
        return `<a href="${WOODFISH_FRIEND_LINK.link}">woodfish</a>`;
      }
      return "";
    });

    const result = await verifyReciprocalLink(
      "https://example.com/links",
      WOODFISH_FRIEND_LINK,
      { fetchText },
    );

    expect(result.found).toBe(false);
    expect(result.checkedUrls).toEqual(["https://example.com/links"]);
    expect(fetchText).toHaveBeenCalledTimes(1);
  });

  it("does not fetch unsafe friend page URLs", async () => {
    const fetchText = vi.fn(async () => `<a href="${WOODFISH_FRIEND_LINK.link}">woodfish</a>`);

    const result = await verifyReciprocalLink(
      "http://127.0.0.1/links",
      WOODFISH_FRIEND_LINK,
      { fetchText },
    );

    expect(result).toEqual({
      checkedUrls: ["http://127.0.0.1/links"],
      found: false,
    });
    expect(fetchText).not.toHaveBeenCalled();
  });

  it("appends a valid YAML friend link only when it is not already present", () => {
    const source = [
      "links:",
      "  - class_name: 友情链接",
      "    descr: 朋友们的网站",
      "    type: item",
      "    link_list:",
      "      - name: woodfish",
      "        link: https://woodfish.site/newBlog/",
      "        avatar: https://example.com/avatar.jpg",
      "        descr: 我喜欢你",
    ].join("\n");

    const first = mergeFriendLinkIntoYaml(source, {
      siteName: "Example: Blog",
      siteUrl: "https://example.com/",
      friendPageUrl: "https://example.com/links",
      avatarUrl: "https://example.com/avatar.png?size=100",
      description: "hello # world",
      contact: "me",
    });

    expect(first.changed).toBe(true);
    expect(first.content).toContain('      - name: "Example: Blog"');
    expect(first.content).toContain('        descr: "hello # world"');

    const second = mergeFriendLinkIntoYaml(first.content, {
      siteName: "Example: Blog",
      siteUrl: "https://example.com/",
      friendPageUrl: "https://example.com/links",
      avatarUrl: "https://example.com/avatar.png?size=100",
      description: "hello # world",
      contact: "me",
    });

    expect(second.changed).toBe(false);
    expect(second.content).toBe(first.content);
  });
});
